#!/bin/bash
# StreamPark 作业提交快速指南
# 用于在 StreamPark Web UI 中提交 Flink 作业

echo "=========================================="
echo "StreamPark 作业提交指南"
echo "=========================================="
echo ""
echo "1. 访问 StreamPark Web UI"
echo "   URL: http://localhost:10000"
echo "   用户名: admin"
echo "   密码: streampark"
echo ""
echo "2. 上传 JAR 包"
echo "   路径: target/realtime-crypto-datawarehouse-1.0.0.jar"
echo ""
echo "3. 创建应用程序"
echo "   - Application Name: FlinkODSJob"
echo "   - Execution Mode: Remote (Flink Standalone)"
echo "   - Flink Version: 1.17"
echo "   - Main Class: com.crypto.dw.flink.FlinkODSJobDataStream"
echo "   - Program Args: (留空)"
echo "   - Dynamic Properties: APP_ENV=dev"
echo ""
echo "4. 提交作业"
echo "   点击 'Start' 按钮启动作业"
echo ""
echo "=========================================="
echo "网络配置验证"
echo "=========================================="
echo ""
echo "验证 Flink 可以访问 Doris FE:"
docker exec flink-jobmanager curl -s http://doris-fe:8030/api/bootstrap | head -1
echo ""
echo "验证 StreamPark 可以访问 Flink JobManager:"
docker exec streampark curl -s http://flink-jobmanager:8081 | head -1
echo ""
echo "=========================================="
echo "配置文件信息"
echo "=========================================="
echo ""
echo "Doris 连接地址 (application-dev.yml):"
echo "  - HTTP URL: http://doris-fe:8030"
echo "  - JDBC URL: jdbc:mysql://doris-fe:9030"
echo ""
echo "Kafka 连接地址:"
echo "  - Bootstrap Servers: localhost:9092"
echo ""
echo "=========================================="
