#!/bin/bash

# StreamPark Dynamic Properties 格式测试脚本
# 用于验证不同格式的 Dynamic Properties 配置

echo "=========================================="
echo "StreamPark Dynamic Properties 格式测试"
echo "=========================================="
echo ""

echo "根据 StreamPark 官方文档，Dynamic Properties 应该使用以下格式之一："
echo ""

echo "格式 1: 标准 Flink -D 格式（推荐）"
echo "  -DAPP_ENV=docker"
echo "  或"
echo "  APP_ENV=docker"
echo ""

echo "格式 2: 多个属性用换行分隔"
echo "  -DAPP_ENV=docker"
echo "  -Dparallelism.default=4"
echo ""

echo "格式 3: 多个属性用空格分隔"
echo "  -DAPP_ENV=docker -Dparallelism.default=4"
echo ""

echo "=========================================="
echo "当前配置建议"
echo "=========================================="
echo ""

echo "在 StreamPark Web UI 的 Dynamic Properties 字段中，尝试以下配置："
echo ""
echo "方式 1（推荐）:"
echo "  -DAPP_ENV=docker"
echo ""
echo "方式 2:"
echo "  APP_ENV=docker"
echo ""
echo "方式 3（如果需要多个属性）:"
echo "  -DAPP_ENV=docker"
echo "  -Dparallelism.default=4"
echo ""

echo "=========================================="
echo "验证方法"
echo "=========================================="
echo ""
echo "1. 在 StreamPark 中配置 Dynamic Properties"
echo "2. 提交作业"
echo "3. 查看作业日志，搜索 '=== 诊断信息 ==='"
echo "4. 检查 'System Property APP_ENV' 的值"
echo ""
echo "如果显示 'System Property APP_ENV: docker'，说明配置成功！"
echo ""

echo "=========================================="
echo "常见问题"
echo "=========================================="
echo ""
echo "Q: 为什么 APP_ENV 读取不到？"
echo "A: 可能的原因："
echo "   1. Dynamic Properties 格式不正确"
echo "   2. 使用了旧的 JAR 包（需要重新上传）"
echo "   3. StreamPark 没有正确传递参数"
echo ""
echo "Q: 应该使用 -D 前缀吗？"
echo "A: 根据 StreamPark 文档，-D 前缀是可选的"
echo "   建议先尝试 '-DAPP_ENV=docker'"
echo "   如果不行，再尝试 'APP_ENV=docker'"
echo ""
echo "Q: 可以配置多个属性吗？"
echo "A: 可以，每行一个属性，或用空格分隔"
echo ""

echo "=========================================="
echo "参考文档"
echo "=========================================="
echo ""
echo "StreamPark 配置文档:"
echo "  https://streampark.apache.org/docs/framework/config"
echo ""
echo "Flink 配置参数:"
echo "  https://nightlies.apache.org/flink/flink-docs-release-1.17/docs/deployment/config/"
echo ""
